# @package experiment.config.monty_config.learning_modules
# Pretraining triple: one displacement LM per sense.
learning_module_0:
  _target_: tbp.monty.frameworks.models.displacement_matching.DisplacementGraphLM
  k: 5
  match_attribute: displacement
learning_module_1:
  _target_: tbp.monty.frameworks.models.displacement_matching.DisplacementGraphLM
  k: 5
  match_attribute: displacement
learning_module_2:
  _target_: tbp.monty.frameworks.models.displacement_matching.DisplacementGraphLM
  k: 5
  match_attribute: displacement
